name: _tanstack_query_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/tanstack_query_core
  - packages/tanstack_query_flutter
  - packages/tanstack_query_flutter/example
  - examples/sensor_demo
