#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the release of query_kit and query_kit_flutter to pub.dev.
# The procedure this automates is docs/releasing.md; that file is the prose,
# this one is the path. Keep them in step.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

REPO="KoTTi97/flutter_query"
CORE_PKG="query_kit"
CORE_DIR="packages/query_kit"
BINDING_PKG="query_kit_flutter"
BINDING_DIR="packages/query_kit_flutter"
PUBLISH_WORKFLOW="publish.yml"

cd "$(git rev-parse --show-toplevel)"

# ── Wizard-local helpers ──────────────────────────────────────────────────

# fail "..." — stop the wizard with a reason. Nothing here is half-done: every
# stage either completes or leaves the world as it found it.
fail() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

# pubspec_version DIR — the `version:` field of the package in DIR.
pubspec_version() {
  grep -E '^version:' "$1/pubspec.yaml" | head -n1 | sed -E 's/^version:[[:space:]]*//'
}

# pub_has_version PKG VERSION — 0 when that exact version is live on pub.dev.
pub_has_version() {
  curl -fsS "https://pub.dev/api/packages/$1/versions/$2" -o /dev/null 2>/dev/null
}

# dry_run DIR PKG — pub's own pre-flight. Its output is only shown on failure,
# because a passing dry-run has nothing worth reading.
dry_run() {
  local dir="$1" pkg="$2" out
  out=$(mktemp)
  if ( cd "$dir" && dart pub publish --dry-run ) >"$out" 2>&1; then
    rm -f "$out"
    ok "$pkg passes dart pub publish --dry-run"
  else
    printf '\n'; sed 's/^/    /' "$out"; printf '\n'; rm -f "$out"
    fail "dry-run failed for $pkg — fix it in $dir, then re-run."
  fi
}

# workflow_state — 'active', 'disabled_manually', or 'unknown'. `gh workflow
# view` has no --json flag, so this reads the REST API directly.
workflow_state() {
  gh api "repos/$REPO/actions/workflows/$PUBLISH_WORKFLOW" --jq .state 2>/dev/null || echo unknown
}

# publish_package DIR PKG VERSION — publish, or say so and skip when the
# version is already live. That is what makes the wizard resumable: an
# interrupted run picks up where it stopped instead of failing on a duplicate.
publish_package() {
  local dir="$1" pkg="$2" version="$3"
  if pub_has_version "$pkg" "$version"; then
    ok "$pkg $version is already on pub.dev — skipping"
    return 0
  fi
  say "Running: dart pub publish   (in $dir)"
  note "pub lists the files, then asks for its own final confirmation."
  printf '\n'
  ( cd "$dir" && dart pub publish )
}

banner "Release $CORE_PKG + $BINDING_PKG to pub.dev"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pre-flight — is this tree releasable?"
say "Nothing is published in this stage. Every check has to pass first."
printf '\n'

command -v dart >/dev/null 2>&1 || fail "dart is not on PATH."
command -v gh   >/dev/null 2>&1 || fail "the gh CLI is not on PATH."
command -v curl >/dev/null 2>&1 || fail "curl is not on PATH."
gh auth status >/dev/null 2>&1  || fail "gh is not authenticated — run: gh auth login"
ok "dart, gh and curl are ready"

branch=$(git rev-parse --abbrev-ref HEAD)
[[ "$branch" == "main" ]] || fail "on branch '$branch' — releases are cut from main."
ok "on main"

[[ -z "$(git status --porcelain)" ]] || fail "working tree is dirty — commit or stash first."
ok "working tree is clean"

git fetch --quiet origin main
[[ "$(git rev-parse HEAD)" == "$(git rev-parse origin/main)" ]] \
  || fail "HEAD and origin/main differ — push or pull first."
ok "in sync with origin/main"

VERSION=$(pubspec_version "$CORE_DIR")
binding_version=$(pubspec_version "$BINDING_DIR")
[[ -n "$VERSION" ]] || fail "could not read a version from $CORE_DIR/pubspec.yaml"
[[ "$VERSION" == "$binding_version" ]] \
  || fail "versions differ: $CORE_PKG is $VERSION, $BINDING_PKG is $binding_version"
ok "both packages are at $VERSION"

grep -qF "$CORE_PKG: ^$VERSION" "$BINDING_DIR/pubspec.yaml" \
  || fail "$BINDING_DIR/pubspec.yaml does not depend on '$CORE_PKG: ^$VERSION'."
ok "the binding depends on $CORE_PKG: ^$VERSION"

for d in "$CORE_DIR" "$BINDING_DIR"; do
  grep -qF "## $VERSION" "$d/CHANGELOG.md" \
    || fail "$d/CHANGELOG.md has no '## $VERSION' heading — pub validates this."
done
ok "both CHANGELOGs have a $VERSION heading"

head_sha=$(git rev-parse HEAD)
ci=$(gh run list --repo "$REPO" --workflow ci.yml --branch main --limit 20 \
       --json headSha,status,conclusion \
       --jq "first(.[] | select(.headSha == \"$head_sha\") | \"\(.status) \(.conclusion)\")" \
     2>/dev/null || true)
case "$ci" in
  "completed success")
    ok "ci is green on ${head_sha:0:7}" ;;
  "")
    warn "no finished ci run found for ${head_sha:0:7}."
    confirm "Release without a green ci run?" || fail "Stopped. Wait for ci, then re-run." ;;
  completed*)
    fail "ci on ${head_sha:0:7} is '${ci#completed }' — green on main is a release precondition." ;;
  *)
    fail "ci on ${head_sha:0:7} is still '$ci' — wait for it to finish." ;;
esac

printf '\n'
say "Running pub's own validation for both packages…"
dry_run "$CORE_DIR" "$CORE_PKG"
dry_run "$BINDING_DIR" "$BINDING_PKG"
printf '\n'
pause "All clear for $VERSION. Press Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "pub.dev — sign in"
say "The first publish of a new package is manual, so the dart CLI needs to be"
say "signed in as the Google account that should own these two names."
printf '\n'
step "A browser window opens — pick the account and grant access."
note "Already signed in? Then this is a no-op."
printf '\n'
pause "Press Enter to run: dart pub login"
printf '\n'
dart pub login || warn "dart pub login reported a problem — pub will ask again when publishing."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The names — the last stop before anything is permanent"
say "A name on pub.dev cannot be freed, renamed or handed over. Publishing"
say "claims '$CORE_PKG' and '$BINDING_PKG' for good."
printf '\n'
open_url "https://pub.dev/packages/$CORE_PKG"
open_url "https://pub.dev/packages/$BINDING_PKG"
printf '\n'
step "Both tabs should 404 — that is what a free name looks like."
step "If either shows a real package, stop: someone else holds that name."
printf '\n'
note "Changing the names instead is one command, and it is not this wizard:"
note "  dart run tool/rename_packages.dart --core <core> --flutter <core>_flutter"
printf '\n'
confirm "Both names are free — claim them permanently?" \
  || fail "Stopped. Nothing was published."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Publish $CORE_PKG $VERSION"
say "The core goes first. pub.dev will not accept the binding while the version"
say "its pubspec names is unresolvable."
printf '\n'
publish_package "$CORE_DIR" "$CORE_PKG" "$VERSION"
printf '\n'
ok "$CORE_PKG $VERSION is published"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Wait for $CORE_PKG $VERSION to become resolvable"
say "pub.dev takes a moment to serve a version it has just accepted. The"
say "binding's publish fails until it does, so the waiting happens here."
printf '\n'
waited=0
until pub_has_version "$CORE_PKG" "$VERSION"; do
  if (( waited >= 300 )); then
    printf '\n'
    warn "still not resolvable after five minutes."
    confirm "Keep waiting?" || fail "Stopped. Re-run the wizard later — it resumes here."
    waited=0
  fi
  printf '  %s… waiting (%ss)%s\r' "$DIM" "$waited" "$RESET"
  sleep 10
  waited=$((waited + 10))
done
printf '                              \r'
ok "pub.dev serves $CORE_PKG $VERSION"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Publish $BINDING_PKG $VERSION"
publish_package "$BINDING_DIR" "$BINDING_PKG" "$VERSION"
printf '\n'
ok "$BINDING_PKG $VERSION is published"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Enable automated publishing for both packages"
say "Both packages now exist, which is the precondition pub.dev puts on this."
say "From here a pushed tag publishes, authenticated by GitHub OIDC — no secrets."
printf '\n'
open_url "https://pub.dev/packages/$CORE_PKG/admin"
step "Automated publishing → 'Enable publishing from GitHub Actions'"
step "Repository:    $REPO"
step "Tag pattern:   $CORE_PKG-v{{version}}"
step "Save."
printf '\n'
pause "Saved for $CORE_PKG? Press Enter for the binding."
printf '\n'
open_url "https://pub.dev/packages/$BINDING_PKG/admin"
step "The same, with the binding's own pattern:"
step "Repository:    $REPO"
step "Tag pattern:   $BINDING_PKG-v{{version}}"
step "Save."
printf '\n'
note "The patterns have to match .github/workflows/$PUBLISH_WORKFLOW, which"
note "triggers on '$CORE_PKG-v*' and '$BINDING_PKG-v*'."
printf '\n'
confirm "Both admin pages saved?" || fail "Stopped before tagging — re-run once both are set."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Tag $VERSION without firing the publish workflow"
CORE_TAG="$CORE_PKG-v$VERSION"
BINDING_TAG="$BINDING_PKG-v$VERSION"

say "$VERSION is on pub.dev already, published by hand, because a brand-new"
say "package cannot be published automatically. Pushing its tags now would start"
say "$PUBLISH_WORKFLOW, which would try to publish $VERSION a second time and"
say "fail — two red runs on the first release, for nothing."
printf '\n'
say "So: disable the workflow, push the tags, enable it again. The tags land,"
say "no run fires, and $VERSION is marked in git exactly like every release"
say "after it."
printf '\n'

workflow_disabled=0
# restore_workflow — a disabled publish workflow that nobody re-enables is the
# expensive failure here, so it is a trap, not a line at the end.
restore_workflow() {
  if (( workflow_disabled )); then
    printf '\n'
    warn "re-enabling $PUBLISH_WORKFLOW…"
    if gh workflow enable "$PUBLISH_WORKFLOW" --repo "$REPO" >/dev/null 2>&1 \
       && [[ "$(workflow_state)" == "active" ]]; then
      ok "$PUBLISH_WORKFLOW is enabled again"
    else
      warn "could not re-enable it — do it by hand:"
      note "  gh workflow enable $PUBLISH_WORKFLOW --repo $REPO"
      SKIPPED+=("re-enable $PUBLISH_WORKFLOW")
    fi
    workflow_disabled=0
  fi
}
trap restore_workflow EXIT

if gh workflow disable "$PUBLISH_WORKFLOW" --repo "$REPO" >/dev/null 2>&1; then
  # Arm the trap on the command succeeding, not on the state read below: if the
  # disable took and the read is merely stale, the workflow must still be
  # re-enabled on the way out.
  workflow_disabled=1
  sleep 3
  if [[ "$(workflow_state)" == "active" ]]; then
    warn "GitHub still reports $PUBLISH_WORKFLOW as active."
    note "The disable may not have propagated; a push now could start a run."
    printf '\n'
    confirm "Push the tags anyway?" || fail "Stopped — re-run in a moment."
  else
    ok "$PUBLISH_WORKFLOW is disabled for the length of the push"
  fi
else
  warn "could not disable $PUBLISH_WORKFLOW — gh may not list a workflow that"
  note "has never run."
  printf '\n'
  say "Pushing anyway costs two failed 'publish' runs ('version already exists')"
  say "and nothing else: the tags land, the published packages are untouched."
  printf '\n'
  confirm "Push the tags and accept the two red runs?" \
    || fail "Stopped. $VERSION is published; only its tags are missing."
fi

git tag -a "$CORE_TAG"    -m "$CORE_PKG $VERSION"    2>/dev/null || note "$CORE_TAG already exists locally"
git tag -a "$BINDING_TAG" -m "$BINDING_PKG $VERSION" 2>/dev/null || note "$BINDING_TAG already exists locally"
git push origin "$CORE_TAG" "$BINDING_TAG"
ok "pushed $CORE_TAG and $BINDING_TAG"

restore_workflow
trap - EXIT

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Verify"
printf '\n'
for pkg in "$CORE_PKG" "$BINDING_PKG"; do
  if pub_has_version "$pkg" "$VERSION"; then
    ok "$pkg $VERSION is live — https://pub.dev/packages/$pkg"
  else
    warn "$pkg $VERSION does not answer yet — check https://pub.dev/packages/$pkg"
    SKIPPED+=("confirm $pkg $VERSION on pub.dev")
  fi
done

state=$(workflow_state)
case "$state" in
  active)
    ok "$PUBLISH_WORKFLOW is active — the next tag publishes on its own" ;;
  unknown)
    warn "could not read the state of $PUBLISH_WORKFLOW — check it by hand."
    SKIPPED+=("check $PUBLISH_WORKFLOW is enabled") ;;
  *)
    warn "$PUBLISH_WORKFLOW is '$state' — enable it:"
    note "  gh workflow enable $PUBLISH_WORKFLOW --repo $REPO"
    SKIPPED+=("enable $PUBLISH_WORKFLOW") ;;
esac

publish_runs=$(gh run list --repo "$REPO" --workflow "$PUBLISH_WORKFLOW" --limit 5 --json conclusion --jq 'length' 2>/dev/null || echo 0)
if [[ "$publish_runs" == "0" ]]; then
  ok "no publish run fired — the tags landed quietly, as intended"
else
  note "$publish_runs publish run(s) exist; expected none on this release"
fi

printf '\n'
note "From the next release on, the manual part is over:"
note "  bump both pubspecs and CHANGELOGs → merge to main → push"
note "  $CORE_PKG-v<new>, then $BINDING_PKG-v<new> once the core resolves."
note "  This wizard's stages 1 and 5 are still the checks worth running by hand."

finish
